#CI项目名
name: MTK-7981-hanwckf

on:
  #自动编译：每月28日国际时间4点，北京时间中午12点执行(北京+8)
  schedule:
    - cron: 0 4 28 * *
  #手动编译
  workflow_dispatch:

#CI权限
permissions: write-all

#CI任务
jobs:
  wrt_config:
    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译平台
      WRT_TARGET: MTK-7981
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: OPENWRT
      #默认WIFI名
      WRT_WIFI: OPENWRT
      #默认密码，仅作提示，修改无用
      WRT_PW: 无
      #默认地址
      WRT_IP: 172.16.10.1
      #默认源码
      WRT_URL: https://github.com/hanwckf/immortalwrt-mt798x.git
      #默认分支
      WRT_BRANCH: openwrt-24.04
      #内存压缩，可选参数，默认关闭，256内存推荐开启
      #WRT_SHRINK: true
